import streamlit as st
import json
import time
import os
from antigravity.infrastructure.state_manager import StateManager
from pathlib import Path

st.set_page_config(page_title="Antigravity 自动化开发产线", layout="wide", page_icon="🚀")

@st.cache_resource
def get_state_manager():
    return StateManager('.')

state_mgr = get_state_manager()

# 1. 顶部：保留 Sentinel 哨兵警报 (Phase 26 的成果)
def get_sentinel_errors(active_root):
    ckpt_dir = Path(active_root) / ".antigravity" / "checkpoints"
    if not ckpt_dir.exists(): return []
    return sorted(list(ckpt_dir.glob("debug_*.json")), key=lambda x: x.stat().st_mtime, reverse=True)

active_root = st.session_state.get('active_project_root', '.')
errors = get_sentinel_errors(active_root)

if errors:
    st.error(f"🛑 [Sentinel] 监测到 {len(errors)} 个运行异常！")
    with st.expander(f"🔍 展开检查最后一个异常的物理现场 ({errors[0].name})"):
        try:
            with open(errors[0], 'r', encoding='utf-8') as f:
                err_data = json.load(f)
            st.warning(f"Error: {err_data.get('error_type')} - {err_data.get('message')}")
            st.code(err_data.get('traceback'), language='python')
        except Exception as e:
            st.error(f"无法读取快照文件: {e}")
            
        if st.button("🗑️ 现场清理并重启执行", key="sentinel_clean_btn"):
            for f in errors:
                try:
                    f.unlink()
                except:
                    pass
            st.rerun()

st.title("🚀 Antigravity 自动化开发产线 (Pure Factory)")

# 2. 核心区：直接展示【新项目全自动发射台】
st.subheader("📦 1. 定义新项目")
col1, col2 = st.columns([1, 1])

with col1:
    project_name = st.text_input("项目名称 (如: DataAnalyzer)", placeholder="my_new_project")
    project_structure = st.text_area("项目内部结构 (每行一个文件)", height=150, placeholder="main.py\nutils/helpers.py\nconfig.json")

with col2:
    uploaded_file = st.file_uploader("📤 上传需求文档 (.txt/.md)", type=['txt', 'md'])
    plan_content = ""
    if uploaded_file:
        plan_content = uploaded_file.getvalue().decode('utf-8')
    
    project_plan = st.text_area("📜 项目执行计划 (PLAN.md)", value=plan_content, height=150)

# 3. 发射按钮与神经重连
if st.button("🔥 物理点火：创建并自动接管", use_container_width=True, type="primary"):
    if not project_name or not project_structure:
        st.error("❌ 项目名称与结构不能为空！")
    else:
        # --- 1. 物理框架建立 ---
        project_dir = Path("projects") / project_name
        project_dir.mkdir(parents=True, exist_ok=True)
        (project_dir / "PLAN.md").write_text(project_plan, encoding="utf-8")
        
        for line in project_structure.split('\n'):
            line = line.strip()
            if line:
                file_path = project_dir / line
                file_path.parent.mkdir(parents=True, exist_ok=True)
                file_path.write_text(f"# Target: {line}\n# TODO: Auto-generated by Antigravity\n", encoding='utf-8')
        
        # --- 2. 🚨 核心修复：主权状态注册 ---
        import time
        from antigravity.infrastructure.p3_state_manager import P3StateManager
        from antigravity.core.mission_orchestrator import MissionOrchestrator, AtomicTask, TaskState
        
        # 将当前新项目设为全局活跃，确保 Monitor 的视线聚焦于此
        p3_mgr = P3StateManager(Path("."))
        p3_mgr.register_project(f"projects/{project_name}")
        p3_mgr.global_state["last_active"] = f"projects/{project_name}"
        p3_mgr._save_global_state()
        
        # --- 3. 🚨 核心修复：发射台任务注入 ---
        # 必须创建任务快照，Monitor 才能穿透状态机并唤起编辑器
        orch = MissionOrchestrator(str(project_dir))
        task = AtomicTask(
            task_id=f"task_{int(time.time())}_{project_name}",
            type="code",
            goal=f"Implement quantitative trading framework for {project_name}",
            metadata={"created_via": "dashboard", "file_path": "PLAN.md"}, # Zero-G 穿透钥匙
            state=TaskState.PENDING
        )
        orch.add_task(task)
        
        # 写入物理快照，唤醒 Monitor 后端引擎
        state_file = project_dir / ".antigravity" / "mission_state.json"
        state_file.parent.mkdir(parents=True, exist_ok=True)
        orch.save_state(str(state_file))
        
        st.success(f"✅ 项目 {project_name} 已成功注册至神经中枢！主权引擎正在物理唤醒...")

# 4. 底部：保留实时的 Audit 历史日志
st.markdown("---")
st.subheader("🔍 实时执行监控")

audits = state_mgr.get_recent_audits(limit=20)
if audits:
    import pandas as pd
    df_data = []
    for audit in reversed(audits[-10:]):
        df_data.append({
            'Time': audit.get('timestamp', '')[:19], 
            'File': audit.get('file_path', ''), 
            'Event': audit.get('event_type', ''), 
            'Status': audit.get('status', '')
        })
    if df_data:
        df = pd.DataFrame(df_data)
        st.dataframe(df, hide_index=True)
else:
    st.info('Waiting for agent activity...')