st.markdown('---')
st.header(t('scaffolding_launcher'))
with st.container():
    p_col1, p_col2 = st.columns([1, 2])
    with p_col1:
        project_name = st.text_input(t('project_name'), placeholder=t('project_name_placeholder'), help=t('project_name_help'), key='p3_project_name')
        st.info('ℹ️ 系统将自动创建标准 P3 项目结构')
        st.caption('包含: main.py, core/, utils/, config/, tests/, data/')
        st.subheader(t('business_doc_upload'))
        uploaded_file = st.file_uploader(t('drag_drop_doc'), type=['txt', 'md'], key='p3_doc_uploader')
        if uploaded_file:
            content = uploaded_file.read().decode('utf-8')
            st.success(t('file_uploaded'))
            with st.expander(t('preview')):
                st.text(content[:500] + '...' if len(content) > 500 else content)
            st.session_state.p3_plan_content = content
    with p_col2:
        st.subheader(t('project_plan'))
        if uploaded_file and st.button(t('apply_to_project_plan'), key='p3_apply_plan'):
            st.session_state.p3_plan_content = content
            st.success(t('plan_updated'))
        plan_display = st.session_state.get('p3_plan_content', t('plan_placeholder'))
        st.text_area(t('current_plan'), value=plan_display, height=350, disabled=True, key='p3_plan_display')
    if st.button(t('create_and_launch'), type='primary', use_container_width=True, key='p3_create_btn'):
        if not project_name:
            st.error(t('error_no_project_name'))
        else:
            try:
                project_path = os.path.join('projects', project_name)
                os.makedirs(project_path, exist_ok=True)
                standard_dirs = ['core', 'utils', 'config', 'tests', 'data']
                for dir_name in standard_dirs:
                    os.makedirs(os.path.join(project_path, dir_name), exist_ok=True)
                template_path = 'PLAN.md'
                if os.path.exists(template_path):
                    with open(template_path, 'r', encoding='utf-8') as f:
                        template_content = f.read()
                    plan_content = template_content.replace('{{PROJECT_NAME}}', project_name)
                    plan_content = plan_content.replace('{{MODULE_NAME}}', f'{project_name.lower()}_core')
                    if st.session_state.get('p3_plan_content'):
                        plan_content += f'\n\n---\n\n## 用户需求文档\n\n{st.session_state.p3_plan_content}'
                else:
                    plan_content = st.session_state.get('p3_plan_content', f'# {project_name} Project Plan\n\nTODO: Define requirements')
                with open(os.path.join(project_path, 'PLAN.md'), 'w', encoding='utf-8') as f:
                    f.write(plan_content)
                standard_files = {'main.py': f'# {project_name} - Main Entry Point\n# Auto-generated by Antigravity P3\n\nfrom pathlib import Path\nimport sys\n\n# Add project root to path\nproject_root = Path(__file__).parent\nsys.path.insert(0, str(project_root))\n\ndef main():\n    """Main entry point"""\n    print(f"🚀 {project_name} starting...")\n    # TODO: Implement according to PLAN.md\n    pass\n\nif __name__ == "__main__":\n    main()\n', 'core/__init__.py': f'# {project_name} Core Module\n', f'core/{project_name.lower()}_core.py': f'# {project_name} - Core Logic\n# Auto-generated by Antigravity P3\n\nfrom typing import Dict, List, Optional\n\nclass {project_name}Core:\n    """Core business logic for {project_name}"""\n    \n    def __init__(self):\n        """Initialize core module"""\n        pass\n    \n    def process(self, data: Dict) -> Optional[Dict]:\n        """\n        Process data according to PLAN.md requirements\n        \n        Args:\n            data: Input data dictionary\n            \n        Returns:\n            Processed result or None\n        """\n        # TODO: Implement according to PLAN.md\n        return None\n', 'utils/__init__.py': f'# {project_name} Utilities\n', 'utils/helpers.py': f'''# {project_name} - Helper Functions\n# Auto-generated by Antigravity P3\n\nfrom typing import Any\nfrom pathlib import Path\n\ndef get_project_root() -> Path:\n    """Get project root directory"""\n    return Path(__file__).parent.parent\n\ndef load_config(config_path: str = "config/settings.json") -> dict:\n    """Load configuration from JSON file"""\n    import json\n    config_file = get_project_root() / config_path\n    if config_file.exists():\n        with open(config_file, 'r', encoding='utf-8') as f:\n            return json.load(f)\n    return {{}}\n''', 'config/settings.json': f'{{\n    "project_name": "{project_name}",\n    "version": "1.0.0",\n    "debug": true\n}}\n', 'tests/__init__.py': f'# {project_name} Tests\n', f'tests/test_{project_name.lower()}_core.py': f'''# Tests for {project_name} Core\n# Auto-generated by Antigravity P3\n\nimport unittest\nimport sys\nfrom pathlib import Path\n\n# Add project root to path\nproject_root = Path(__file__).parent.parent\nsys.path.insert(0, str(project_root))\n\nfrom core.{project_name.lower()}_core import {project_name}Core\n\nclass Test{project_name}Core(unittest.TestCase):\n    def setUp(self):\n        self.core = {project_name}Core()\n    \n    def test_initialization(self):\n        """Test core module initialization"""\n        self.assertIsNotNone(self.core)\n    \n    def test_process(self):\n        """Test process method"""\n        # TODO: Add real tests according to PLAN.md\n        result = self.core.process({{}})\n        self.assertIsNone(result)  # Placeholder\n\nif __name__ == '__main__':\n    unittest.main()\n''', 'data/.gitkeep': '# Data directory\n'}
                created_files = []
                for file_path, content in standard_files.items():
                    full_path = os.path.join(project_path, file_path)
                    os.makedirs(os.path.dirname(full_path), exist_ok=True)
                    with open(full_path, 'w', encoding='utf-8') as f:
                        f.write(content)
                    created_files.append(file_path)
                st.balloons()
                st.success(t('project_created').format(project_name))
                with st.expander(t('created_files')):
                    for f in created_files:
                        st.text(f'✅ projects/{project_name}/{f}')
                st.info('🎯 ' + t('auto_focusing_project'))
                from pathlib import Path
                from antigravity.infrastructure.p3_state_manager import P3StateManager
                project_path_obj = Path('projects') / project_name
                st.session_state.last_selected_project = None
                st.session_state.active_project_root = project_path_obj
                try:
                    st.session_state.active_state_mgr = P3StateManager(project_path_obj)
                    try:
                        from antigravity.infrastructure.performance_monitor import PerformanceMonitor
                        st.session_state.active_perf_monitor = PerformanceMonitor(str(project_path_obj))
                    except:
                        st.session_state.active_perf_monitor = None
                    st.success('✅ ' + t('project_auto_focused'))
                except Exception as e:
                    st.warning(f'⚠️ Auto-focus initialization: {e}')
                state_mgr.log_audit(f'projects/{project_name}', 'project_scaffolding', f'Created project with {len(created_files)} files', 'INFO')
                st.rerun()
            except Exception as e:
                st.error(t('project_creation_failed').format(e))
                import traceback
                st.code(traceback.format_exc(), language='python')