# 小红书爬虫 - Main Entry Point
# Auto-generated by Antigravity P3

import asyncio
import json
import logging
import sys
from pathlib import Path
from typing import Dict, Any, Optional

# Add project root to path
project_root = Path(__file__).parent
sys.path.insert(0, str(project_root))

# Import project modules
try:
    from core.xiaohongshu_crawler import XiaohongshuCrawler
    from utils.helpers import setup_logging, validate_config, retry_with_exponential_backoff
except ImportError as e:
    print(f"❌ 导入模块失败: {e}")
    print("请确保项目结构完整，并已安装所有依赖")
    sys.exit(1)


class XiaohongshuSpider:
    """小红书爬虫主控制器"""
    
    def __init__(self, config_path: Optional[Path] = None):
        """
        初始化爬虫
        
        Args:
            config_path: 配置文件路径，默认为 config/settings.json
        """
        self.project_root = Path(__file__).parent
        self.config_path = config_path or self.project_root / "config" / "settings.json"
        self.config: Dict[str, Any] = {}
        self.crawler: Optional[XiaohongshuCrawler] = None
        self.logger = logging.getLogger(__name__)
    
    def track_performance(self, func):
        """性能监控装饰器（简化版）"""
        def wrapper(*args, **kwargs):
            import time
            start_time = time.time()
            instance = args[0] if args else None
            func_name = func.__name__
            
            if instance and hasattr(instance, 'logger'):
                instance.logger.debug(f"开始执行: {func_name}")
            
            try:
                result = func(*args, **kwargs)
                elapsed = time.time() - start_time
                
                if instance and hasattr(instance, 'logger'):
                    instance.logger.debug(f"完成执行: {func_name}, 耗时: {elapsed:.2f}秒")
                
                return result
            except Exception as e:
                elapsed = time.time() - start_time
                if instance and hasattr(instance, 'logger'):
                    instance.logger.error(f"执行失败: {func_name}, 耗时: {elapsed:.2f}秒, 错误: {e}")
                raise
        
        return wrapper
    
    @track_performance
    def load_config(self) -> bool:
        """
        加载配置文件
        
        Returns:
            bool: 配置加载是否成功
        """
        try:
            if not self.config_path.exists():
                self.logger.error(f"配置文件不存在: {self.config_path}")
                return False
                
            with open(self.config_path, 'r', encoding='utf-8') as f:
                self.config = json.load(f)
                
            # 验证必要配置
            required_keys = ['api_keys', 'crawler_settings', 'output_settings']
            for key in required_keys:
                if key not in self.config:
                    self.logger.error(f"配置缺少必要字段: {key}")
                    return False
                    
            self.logger.info("配置文件加载成功")
            return True
            
        except json.JSONDecodeError as e:
            self.logger.error(f"配置文件格式错误: {e}")
            return False
        except Exception as e:
            self.logger.error(f"加载配置文件时发生错误: {e}")
            return False
    
    @track_performance
    def initialize_environment(self) -> bool:
        """
        初始化运行环境
        
        Returns:
            bool: 环境初始化是否成功
        """
        try:
            # 检查数据目录
            data_dir = self.project_root / "data"
            data_dir.mkdir(exist_ok=True)
            self.logger.info(f"数据目录已准备: {data_dir}")
            
            # 检查浏览器环境
            # 这里可以添加Playwright浏览器检查逻辑
            # 暂时只记录日志
            self.logger.info("环境检查完成")
            return True
            
        except Exception as e:
            self.logger.error(f"环境初始化失败: {e}")
            return False
    
    @retry_with_exponential_backoff(max_retries=3)
    @track_performance
    async def run_crawler(self) -> bool:
        """
        运行爬虫主逻辑
        
        Returns:
            bool: 爬虫执行是否成功
        """
        try:
            # 初始化爬虫
            self.crawler = XiaohongshuCrawler(self.config)
            
            # 执行爬虫任务
            self.logger.info("开始执行小红书爬虫任务...")
            
            # 根据配置执行不同的爬虫任务
            tasks = self.config.get('crawler_settings', {}).get('tasks', [])
            
            for task in tasks:
                task_type = task.get('type', '')
                target = task.get('target', '')
                
                if not task_type or not target:
                    self.logger.warning(f"跳过无效任务: {task}")
                    continue
                    
                self.logger.info(f"执行任务: {task_type} - {target}")
                
                if task_type == 'user_profile':
                    result = await self.crawler.crawl_user_profile(target)
                elif task_type == 'user_posts':
                    result = await self.crawler.crawl_user_posts(target)
                elif task_type == 'search_keyword':
                    keyword = target
                    limit = task.get('limit', 10)
                    result = await self.crawler.search_keyword(keyword, limit)
                else:
                    self.logger.warning(f"未知任务类型: {task_type}")
                    continue
                
                if result:
                    self.logger.info(f"任务完成: {task_type} - {target}")
                else:
                    self.logger.error(f"任务失败: {task_type} - {target}")
            
            return True
            
        except Exception as e:
            self.logger.error(f"爬虫执行失败: {e}")
            return False
    
    @track_performance
    async def run(self) -> bool:
        """
        运行主流程
        
        Returns:
            bool: 整个流程是否成功
        """
        try:
            # 1. 设置日志
            setup_logging()
            self.logger.info("🚀 小红书爬虫启动中...")
            
            # 2. 加载配置
            if not self.load_config():
                return False
                
            # 3. 初始化环境
            if not self.initialize_environment():
                return False
                
            # 4. 验证配置
            if not validate_config(self.config):
                self.logger.error("配置验证失败")
                return False
                
            # 5. 运行爬虫
            success = await self.run_crawler()
            
            if success:
                self.logger.info("✅ 小红书爬虫任务完成")
            else:
                self.logger.error("❌ 小红书爬虫任务失败")
                
            return success
            
        except KeyboardInterrupt:
            self.logger.info("⏹️ 用户中断执行")
            return False
        except Exception as e:
            self.logger.error(f"❌ 程序执行异常: {e}")
            return False


def main():
    """Main entry point"""
    spider = XiaohongshuSpider()
    
    # 运行异步主函数
    try:
        success = asyncio.run(spider.run())
        sys.exit(0 if success else 1)
    except RuntimeError as e:
        if "Event loop is closed" in str(e):
            # 忽略事件循环关闭的错误
            pass
        else:
            print(f"❌ 运行时错误: {e}")
            sys.exit(1)


if __name__ == "__main__":
    main()